# Generated by Django 6.0 on 2025-12-22 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='The Writing Hub Tz', max_length=255)),
                ('tagline', models.CharField(blank=True, default='Empowering Excellence through Words', max_length=500)),
                ('phone', models.CharField(blank=True, default='+255 (0) 717 313797', max_length=20)),
                ('email', models.EmailField(blank=True, default='thewritinghubtz@gmail.com', max_length=254)),
                ('website', models.URLField(blank=True, default='www.thewritinghutz.net')),
                ('address', models.TextField(blank=True, default='9 Floor, Elite Towers, Azikiwe St, Dar es Salaam, Tanzania')),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True, default='the_writing_hub_tz')),
                ('founder_name', models.CharField(blank=True, default='Frank Mhando (MA., PhD. DT)', max_length=255)),
                ('founder_title', models.CharField(blank=True, default='Founder', max_length=255)),
                ('founder_affiliation', models.CharField(blank=True, default='University of Johannesburg, SA', max_length=255)),
                ('advisor_name', models.CharField(blank=True, default='Prof. Donaldson F. Conserve', max_length=255)),
                ('advisor_title', models.CharField(blank=True, default='Advisor', max_length=255)),
                ('advisor_affiliation', models.CharField(blank=True, default='The George Washington University, USA', max_length=255)),
                ('company_story', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True, default='To be the leading catalyst for academic, research and professional success by fostering exceptional writing skills and promoting impactful communication.')),
                ('mission', models.TextField(blank=True, default='At The Writing Hub Tz, our mission is to provide comprehensive writing solutions, research and development support, educational support and to empowering individuals and organisations in achieving their goals. We strive to offer unparalleled guidance, coaching, and workshops that cultivate strong writing abilities and research acumen. With a commitment to excellence, we aim to bridge the gap between ideas and expression, enabling our clients to make a lasting impact in academia and beyond.')),
                ('why_choose_us', models.TextField(blank=True, default="Choose 'The Writing Hub Tz' for expert guidance and personalized support in academic writing, research and development services, workshops, business write-ups, and streamlined government application facilitation. With a proven track record, our experienced team is committed to empowering you to excel in your academic, research, professional, and entrepreneurial pursuits.")),
                ('registration_year', models.IntegerField(blank=True, default=2023)),
                ('established_year', models.IntegerField(blank=True, default=2018)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
        migrations.CreateModel(
            name='ConsultancySubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('consultancy_type', models.CharField(choices=[('business_tax', 'Business & Tax Consulting'), ('business_strategy', 'Business Strategy & Planning'), ('investment', 'Investment Facilitation'), ('proposal_support', 'Proposal & Academic Wig Support'), ('training_capacity', 'Training & Capacity Building'), ('academic', 'Academic Consultancy'), ('research', 'Research Consultancy'), ('career', 'Career Consultancy'), ('writing', 'Writing Consultancy')], max_length=50)),
                ('description', models.TextField()),
                ('detailed_description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, help_text='List of features/items, one per line')),
                ('icon', models.CharField(default='ri-discuss-line', help_text='e.g., ri-briefcase-line, ri-team-line', max_length=100)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('customer_type', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], default='individual', max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_contact', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('service_update', 'Service Update'), ('workshop_reminder', 'Workshop Reminder'), ('message', 'Message'), ('system', 'System')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category', models.CharField(choices=[('concept_proposal', 'Concept Proposal'), ('thesis', 'Thesis Writing'), ('articles', 'Article Writing'), ('data_analysis', 'Data Analysis'), ('research_design', 'Research Design'), ('consultancy', 'Consultancy'), ('training_capacity', 'Training & Capacity Building')], max_length=50)),
                ('description', models.TextField()),
                ('detailed_description', models.TextField(blank=True)),
                ('icon', models.CharField(default='ri-file-text-line', max_length=100)),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('turnaround_time', models.CharField(blank=True, help_text="e.g., '5-7 business days'", max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['category'], name='tracker_res_categor_c5e641_idx'), models.Index(fields=['is_active'], name='tracker_res_is_acti_e229bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('quote', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='tracker.customer')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='tracker.researchservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes from admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='tracker.customer')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='tracker.researchservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('phone_verified', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('newsletter_subscribed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField()),
                ('detailed_description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_online', models.BooleanField(default=False)),
                ('meeting_url', models.URLField(blank=True, help_text='Zoom/Teams link for online workshops')),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('cancelled', 'Cancelled'), ('no_show', 'No-show')], default='registered', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('special_requirements', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_registrations', to='tracker.customer')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tracker.workshop')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='tracker_cus_email_288fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active'], name='tracker_cus_is_acti_ba0131_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='tracker_not_is_read_9b3a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user'], name='tracker_not_user_id_7060d7_idx'),
        ),
        migrations.AddIndex(
            model_name='clienttestimonial',
            index=models.Index(fields=['is_published'], name='tracker_cli_is_publ_f54ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='clienttestimonial',
            index=models.Index(fields=['is_featured'], name='tracker_cli_is_feat_1dab7c_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status'], name='tracker_ser_status_460540_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['customer'], name='tracker_ser_custome_14fb8f_idx'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['date'], name='tracker_wor_date_580a84_idx'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['is_active'], name='tracker_wor_is_acti_ad5ea1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workshopregistration',
            unique_together={('workshop', 'customer')},
        ),
    ]
