# Generated by Django 6.0 on 2026-01-02 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_link', models.URLField(help_text='Zoom meeting link')),
                ('zoom_meeting_id', models.CharField(blank=True, help_text='Zoom meeting ID', max_length=100)),
                ('passcode', models.CharField(blank=True, help_text='Zoom meeting passcode', max_length=100)),
                ('password', models.CharField(blank=True, help_text='Additional password if needed', max_length=100)),
                ('start_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zoom_appointments', to='tracker.consultancysubservice')),
                ('workshop', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zoom_appointment', to='tracker.workshop')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
